services:
  db:
    image: postgres:16
    container_name: dev-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repositorio
    ports:
      - "5433:5432"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./docker/postgres-data:/var/lib/postgresql/data
      - ./storage:/etc/storage
