services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app/apps/backend:rw
      - /app/apps/backend/node_modules
    command: npm run start:dev
    working_dir: /app/apps/backend
    environment:
      NODE_ENV: development
  dev_database:
    image: postgres:15
    container_name: app-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repositorio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
